### ISSUE TITLE
Is it possible to use more than 54GB RAM in JDK11 Build jdk-11.0.15+10

### ISSUE THREAD

**Issue by philipphomberger** [adoptium/jdk11u#12]
Hello All, 
Is it possible to use more than 54GB RAM in JDK11 Build jdk-11.0.15+10
Thank You 
With Regards 
Philipp Homberger

**Comment by karianna** [comment]
In short, yes.

**Comment by philipphomberger** [comment]
@karianna  Thank You for that Information. Maybe a short question from my side. In the past we use always the Large Heap buid from AdoptOpenJDK OpenJ9 Build. Because of that I was thinking that there is a limitation on the other Builds. Does that mean I can just download the latest Java and set the heap size as I like, right?

**Comment by karianna** [comment]
That is correct.
