### ISSUE TITLE
Backport Portola to jdk11u (For Alpine musl build support)

### ISSUE THREAD

**Issue by karianna** [adoptium/jdk11u#4]
We are taking the best of the Bellsoft and Azul patches to their jdk11u distributions (a big thank you to them!) and applying that here for testing with the Adoptium community before Bellsoft submits the patch to OpenJDK proper.

**Comment by karianna** [comment]
@calderast - is working on this

**Comment by gdams** [comment]
The work here is done. We will produce a release this week
